### ISSUE TITLE
Tool does not launch due to missing png's for UI

### ISSUE THREAD

**Issue by JoKr4** [KingKeule/VPNubt#11]
> 2020/11/12 18:24:18 Could not find the ressource
> 2020/11/12 18:24:18 open img\icons8-tunnel-24.png: Das System kann den angegebenen Pfad nicht finden.

This file should be part of release package.

Fix for now is to download the png and place it manually in a new folder "img" next to the exe

**Comment by KingKeule** [comment]
Bug is fixed @ v1.1.
Image is embedded directly into file with GO v1.16.
